blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListView.as_view(), name="blog_views"),
    path("view/<int:pk>", BlogDetailView.as_view(), name="blog_detail"),
    path("create/", never_cache(BlogCreateView.as_view()), name="blog_create"),
    path("<int:pk>/update/", never_cache(BlogUpdateView.as_view()), name="blog_update"),
    path("<int:pk>/delete/", BlogDeleteView.as_view(), name="blog_delete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from users.models import User


class Blog(models.Model):
    """
    Модель блога
    """
    title = models.CharField(
        max_length= 250,
        verbose_name='Заголовок',
        help_text='Укажите заголовок блога'
    )
    slug = models.CharField(
        max_length=250,
        verbose_name="slug",
        null=True,
        blank=True
    )
    content = models.TextField(
        verbose_name='Содержимое',
        help_text='Введите текст блога',
        null=True,
        blank=True
    )
    image = models.ImageField(
        upload_to='blog/',
        verbose_name="Изображение",
        help_text='Загрузите изображение для блога',
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания',
        help_text='Введите дату создания блога'
    )
    is_published = models.BooleanField(
        default=False,
        verbose_name='Опубликовано',
        help_text='Отметьте, если блог опубликован'
    )
    views_count = models.PositiveIntegerField(
        default=0,
        verbose_name='Просмотры',
        editable=False,
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        verbose_name='Создатель карточки блога',
        blank=True,
        null=True,
        related_name='blogs_users'  # related_name для получения всех блогов пользователя
    )

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"
        ordering = ['created_at']

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.image.delete()
        super(Blog, self).delete(*args, **kwargs)

blog/forms.py
from django.forms import ModelForm

from blog.models import Blog


class BlogFrom(ModelForm):
    """
    Форма для создания и редактирования публикации блога
    """
    class Meta:
        model = Blog
        fields = ('title', 'content', 'image', 'is_published')

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.forms import BlogFrom
from blog.models import Blog


class BlogListView(ListView):
    """
    Выводит список всех публикаций блога
    """
    model = Blog

    def get_queryset(self, *args, **kwargs):
        """
        Получает все публикации блога, которые опубликованы
        """
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(LoginRequiredMixin, DetailView):
    """
    Выводит конкретную публикацию блога с подробным описанием и картинкой
    """
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save(update_fields=['views_count'])
        return self.object


class BlogCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """
    Выводит страницу для создания новой публикации блога
    """
    model = Blog
    form_class = BlogFrom
    success_url = reverse_lazy('blog:blog_views')
    permission_required = 'blog.add_blog'

    def form_valid(self, form):
        """
        Проверяет данные на валидность и генерирует слаг
        """
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.owner = self.request.user
            new_mat.save(update_fields=['slug', 'owner'])
        return super().form_valid((form))


class BlogUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """
    Выводит страницу для редактирования конкретной публикации блога
    """
    model = Blog
    form_class = BlogFrom
    success_url = reverse_lazy('blog:blog_views')
    permission_required = 'blog.change_blog'

    def get_success_url(self):
        """
        Возвращает URL страницы с детальным описанием публикации блога
        """
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    """
    Выводит страницу для удаления конкретной публикации блога
    """
    model = Blog
    success_url = reverse_lazy('blog:blog_views')
    permission_required = 'blog.delete_blog'

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html'%}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% if object.image %}
                    <img class="card-img-top" src="{{ object.image| mymedia }}"
                         style="max-width: 600px; max-height: 400px">
                    {% else %}
                    <img src="/media/blog/dd70ce88-0468-427b-9b4b-e3b4b4ddf6f0.jpeg"
                         style="max-width: 400px; max-height: 180px">
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить блог"{{ object }}"</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'blog:blog_detail' object.pk %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Статья</h1>
    <h3 class="lead">{{ object.title }} ({{ object.slug }})</h3>
</div>

<div class="container">

    <div class="row text-center">
        <div class="col">
            <div class="card box-shadow">

                <div class="card-header">
                    {% if object.image %}
                    <img class="card-img-top" src="{{ object.image| mymedia }}"
                         style="max-width: 600px; max-height: 400px">
                    {% else %}
                    <img src="/media/blog/dd70ce88-0468-427b-9b4b-e3b4b4ddf6f0.jpeg"
                         style="max-width: 400px; max-height: 180px">
                    {% endif %}


                </div>
                <div class="card-body">
                    <p> {{ object.content }}</p>
                    {% if perms.blog.change_blog and perms.blog.delete_blog or user.is_superuser %}
                    <a class="btn btn-lg btn-block btn-outline-warning"
                       href="{% url 'blog:blog_update' object.pk %}"
                       role="button">Изменить</a>
                    <a class="btn btn-lg btn-block btn-outline-danger"
                       href="{% url 'blog:blog_delete' object.pk%}"
                       role="button">Удалить</a>
                    {% endif %}
                    <a href="{% url 'blog:blog_views' %}" type="button"
                       class="btn btn-lg btn-block btn-outline-primary">Назад</a>
                    <p class="card-text">
                        <small class="text-muted">Просмотры: {{ object.views_count }}</small>
                    </p>
                </div>

            </div>
        </div>
    </div>

    {% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p}}
                        <button type="submit" class="btn btn-success">

                            {% if not object %}
                            Создать
                            {% else %}
                            Обновить
                            {% endif %}
                        </button>
                        {% if object %}
                        <a href="{% url 'blog:blog_detail' object.pk%}" type="button" class="btn btn-danger">Отмена</a>
                        {% else %}
                        <a href="{% url 'blog:blog_views' %}" type="button" class="btn btn-danger">Отмена</a>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">БЛОГ</h1>
    <p class="lead">Мысли в слух</p>
</div>

<div class="container">

    <div class="row text-center">
        {% if user.is_authenticated %}
        <p>
            <a class="btn btn-lg btn-block btn-outline-warning"
               href="{% url 'blog:blog_create' %}"
               role="button">Добавить статью</a>
        </p>
        {% endif %}

        {% for blog in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow" style="max-width: 600px; min-height: 500px">

                <div class="card-header" style="min-width: 200px; min-height: 80px">
                    <h4 class="my-0 font-weight-normal">{{ blog.title }}</h4>
                </div>

                {% if blog.image %}
                <img src="{{ blog.image| mymedia }}" style="max-width: 400px; max-height: 180px">
                {% else %}
                <img src="/media/blog/dd70ce88-0468-427b-9b4b-e3b4b4ddf6f0.jpeg" style="max-width: 400px; max-height: 180px">
                {% endif %}
                <div class="card-body">

                    <p class="card-text">
                        <p class="text-muted">{{ blog.content | truncatechars:100 }}</p>

                    <a class="btn btn-lg btn-block btn-outline-primary"
                       href="{% url 'blog:blog_detail' blog.pk %}"
                       role="button">Просмотр статьи</a>

                </div>

            </div>
        </div>
        {% endfor %}
    </div>

{% endblock %}