blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListView.as_view(), name="blog_views"),
    path("view/<int:pk>", BlogDetailView.as_view(), name="blog_detail"),
    path("create/", never_cache(BlogCreateView.as_view()), name="blog_create"),
    path("<int:pk>/update/", never_cache(BlogUpdateView.as_view()), name="blog_update"),
    path("<int:pk>/delete/", BlogDeleteView.as_view(), name="blog_delete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.apps import CatalogConfig
from catalog.views import (ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView,
                           ProductDeleteView, ContactView, CategoryListView)

app_name = CatalogConfig.name

urlpatterns = [
    path("", ProductListView.as_view(), name="product_views"),
    path("product/<int:pk>", cache_page(60)(ProductDetailView.as_view()), name="product_detail"),
    path("product/create/", never_cache(ProductCreateView.as_view()), name="product_create"),
    path("product/<int:pk>/update/", never_cache(ProductUpdateView.as_view()), name="product_update"),
    path("product/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"),

    path("contacts/", ContactView.as_view(), name="contacts"),

    path("product/category/view", CategoryListView.as_view(), name="category_list"),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserRegisterView, email_verification, GeneratePasswordView, ProfileUpdateView, ProfileDetailView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('email-confirm/<str:token>', email_verification, name='email-confirm'),
    path('recover_password/', GeneratePasswordView.as_view(), name='recover-password'),
    path('update-profile/<int:pk>', ProfileUpdateView.as_view(), name='update-profile'),
    path('profile/<int:pk>', ProfileDetailView.as_view(), name='profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """
    Модель Пользователя
    """
    username = None

    email = models.EmailField(
        unique=True,
        verbose_name='email',
    )
    phone = models.CharField(
        max_length=35,
        verbose_name='Телефон',
        blank=True,
        null=True,
    )
    avatar = models.ImageField(
        upload_to='users/',
        verbose_name='Аватар',
        blank=True,
        null=True
    )
    country = models.CharField(
        max_length=50,
        verbose_name='Страна',
        blank=True,
        null=True
    )
    token = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        verbose_name='Токен'
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm
from django.forms import ModelForm

from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class PasswordForm(StyleFormMixin, PasswordResetForm):
    class Meta:
        model = User
        fields = ('email',)


class UserUpdateForm(StyleFormMixin, ModelForm):
    class Meta:
        model = User
        fields = ('phone', 'avatar', 'country', )

users/views.py
import secrets
import string
import random


from django.contrib.auth.views import PasswordResetView
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, DetailView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, PasswordForm, UserUpdateForm
from users.models import User


class UserRegisterView(CreateView):
    """
    Регистрация нового пользователя с подтверждением почты
    и генерацией токена подтверждения
    """
    model = User
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        host = self.request.get_host()
        token = secrets.token_hex(16)
        user.token = token
        user.save(update_fields=['token', 'is_active'])
        url = f'http://{host}/users/email-confirm/{token}'
        send_mail(
            "Подтверждение почты",
            f'Пройдите по ссылке для подтверждения почты {url}',
            EMAIL_HOST_USER,
            [user.email]
        )
        return super().form_valid(form)


def email_verification(request, token):
    """
    Перевод пользователя в статуc Активный при проходе по ссылке с почты
    """
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save(update_fields=['is_active'])
    return redirect(reverse('users:login'))


class GeneratePasswordView(PasswordResetView):
    """
    Генерация пароля при нажатии на кнопку "Восстановить пароль"
    c генерируемым новым паролем
    """
    model = User
    form_class = PasswordForm
    template_name = "users/recover_password.html"
    success_url = reverse_lazy("users/login.html")

    def form_valid(self, form):
        email = form.cleaned_data['email']
        user = get_object_or_404(User, email=email)
        symbols = list(string.ascii_letters + string.digits + "!@#$%^&*()")
        random.shuffle(symbols)
        new_password = "".join(symbols[:13])
        user.set_password(new_password)
        user.save()
        send_mail(
            "Сброс пароля",
            f'Ваш новый пароль: {new_password}',
            EMAIL_HOST_USER,
            [user.email]
        )
        return redirect(reverse('users:login'))


class ProfileDetailView(DetailView):
    """
    Вывод информации о пользователе
    """
    model = User


class ProfileUpdateView(UpdateView):
    """
    Вывод формы редактирования профиля пользователя
    """
    model = User
    form_class = UserUpdateForm

    def get_success_url(self):
        """
        Возвращает URL для перехода на детальную страницу пользователя после успешного редактирования
        """
        return reverse('users:profile', kwargs={'pk': self.object.pk})

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title"> Вход</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p}}
                        <button type="submit" class="btn btn-success">Войти</button>
                        <a href="{% url 'catalog:product_views' %}" type="button" class="btn btn-danger">Отмена</a>
                        <a href="{% url 'users:recover-password' %}" type="button" class="btn btn-primary">Восстановить пароль</a>

                    </div>
                </div>
            </div>
        </form>
    </div>

    {% endblock %}

users/templates/users/recover_password.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Востановление пароля</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p}}
                        <button type="submit" class="btn btn-success">Восстановить</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

    {% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Регистрация нового профиля</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p}}
                        <button type="submit" class="btn btn-success">Зарегистрировать</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

    {% endblock %}

users/templates/users/user_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Личный кабинет пользователя</h1>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col">
            <div class="card mb-4 box-shadow">

                <div class="card-header">
                    <h1 class="my-0 font-weight-normal">{{ object.email }}</h1>
                </div>

                <div class="card-body">
                    {% if object.avatar %}
                    <img class="card-img-top" src="{{ object.avatar| mymedia }}"
                         style="max-width: 600px; max-height: 400px">
                    {% else %}
                    <img src="/media/product/dd70ce88-0468-427b-9b4b-e3b4b4ddf6f0.jpeg"
                         style="max-width: 400px; max-height: 190px">
                    {% endif %}
                    <p> {{ object.phone }}</p>
                    <p> {{ object.country }}</p>
                    <a href="{% url 'users:update-profile' object.pk %}" type="button"
                       class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>
                    <a href="{% url 'catalog:product_views' %}" type="button"
                       class="btn btn-lg btn-block btn-outline-primary">Назад</a>

                </div>

            </div>
        </div>
    </div>

    {% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Редактирование профиля</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p}}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                        <a href="{% url 'users:profile' object.pk %}" type="button" class="btn btn-danger">Отмена</a>
                    </div>
                </div>
            </div>
        </form>
    </div>

    {% endblock %}