blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListView.as_view(), name="blog_views"),
    path("view/<int:pk>", BlogDetailView.as_view(), name="blog_detail"),
    path("create/", never_cache(BlogCreateView.as_view()), name="blog_create"),
    path("<int:pk>/update/", never_cache(BlogUpdateView.as_view()), name="blog_update"),
    path("<int:pk>/delete/", BlogDeleteView.as_view(), name="blog_delete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.apps import CatalogConfig
from catalog.views import (ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView,
                           ProductDeleteView, ContactView, CategoryListView)

app_name = CatalogConfig.name

urlpatterns = [
    path("", ProductListView.as_view(), name="product_views"),
    path("product/<int:pk>", cache_page(60)(ProductDetailView.as_view()), name="product_detail"),
    path("product/create/", never_cache(ProductCreateView.as_view()), name="product_create"),
    path("product/<int:pk>/update/", never_cache(ProductUpdateView.as_view()), name="product_update"),
    path("product/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"),

    path("contacts/", ContactView.as_view(), name="contacts"),

    path("product/category/view", CategoryListView.as_view(), name="category_list"),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models, connection

from users.models import User


class Category(models.Model):
    """
    Модель категории продукта
    """
    name = models.CharField(
        max_length=100,
        verbose_name="Наименование",
        help_text="Введите наименование категории",
    )
    description = models.TextField(
        verbose_name="Описание",
        help_text="Введите описание категории",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["name"]

    def __str__(self):
        return self.name

    @classmethod
    def truncate_table_restart_id(cls):
        with connection.cursor() as cursor:
            cursor.execute(
                f"TRUNCATE TABLE {cls._meta.db_table} RESTART IDENTITY CASCADE"
            )


class Product(models.Model):
    """
    Модель продукта
    """
    name = models.CharField(
        max_length=100,
        verbose_name="Наименование",
        help_text="Введите наименование продукта",
    )
    description = models.TextField(
        verbose_name="Описание",
        help_text="Введите описание продукта"
    )
    images = models.ImageField(
        upload_to="product/",
        verbose_name="Изображение",
        help_text="Загрузите изображение продукта",
        blank=True,
        null=True,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        verbose_name="Категория",
        help_text="Выберите категорию товара",
        blank=True,
        null=True,
        related_name="products",
    )
    price = models.IntegerField(
        verbose_name="Цена",
        default=0,
        help_text="введите цену на единицу товара",
        blank=True,
        null=True,
    )
    created_at = models.DateField(
        auto_now_add=True,
        verbose_name="Дата создания",
        help_text="Введите дату записи в базу данных",
        blank=True,
        null=True,
    )
    updated_at = models.DateField(
        auto_now=True,
        verbose_name="Дата последнего изменения",
        help_text="Введите дату последнего изменения",
        blank=True,
        null=True,
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        verbose_name='Создатель карточки продукта',
        blank=True,
        null=True,
    )
    is_published = models.BooleanField(
        default=False,
        verbose_name='Опубликовано',
    )

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name", "price"]
        permissions = [
            ('can_edit_is_published', 'can_edit_is_published'),
            ('can_edit_description', 'can_edit_description'),
            ('can_edit_category', 'can_edit_category')
        ]

    def __str__(self):
        return self.name

    @property
    def active_version(self):
        """
        Возвращает активную версию продукта в ListView
        """
        return self.versions.filter(current_version_flag=True).first()

    def delete(self, *args, **kwargs):
        self.images.delete()
        super(Product, self).delete(*args, **kwargs)


class Version(models.Model):
    """
    Модель версии продукта
    """
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name="Наименование продукта",
        help_text="Выберите продукт",
        related_name="versions",
    )
    number_version = models.FloatField(
        verbose_name="Номер версии",
        help_text="Введите номер версии продукта",
    )
    name_version = models.CharField(
        max_length=250,
        verbose_name="Название версии",
        help_text="Введите название версии продукта",
        null=True,
        blank=True,
    )
    current_version_flag = models.BooleanField(
        verbose_name="Текущая версия",
        help_text="Установите флаг текущей версии",
    )

    def __str__(self):
        return f'{self.number_version}'

    class Meta:
        verbose_name = 'Версия продукта'
        verbose_name_plural = 'Версии продуктов'
        ordering = ('number_version',)

catalog/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm, BooleanField

from catalog.models import Product, Version


class StyleFormMixin:
    """
    Mixin для стилизации формы.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, ModelForm):
    """
    Форма добавления и редактирования продукта.
    """
    class Meta:
        model = Product
        exclude = ['created_at', 'updated_at', 'owner', 'is_published']

    @staticmethod
    def valid_text(text):
        """
        Проверка текста на наличие запрещенных слов.
        """
        edited_text = text.lower().strip(' ,.!:" ').replace('.', '').replace(',', '').split()
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        for word in edited_text:
            if word in forbidden_words:
                raise ValidationError('Имеется запрещенное слово, используете только разрешенные слова')
        else:
            return text

    def clean_name(self):
        """
        Проверка названия продукта на наличие запрещенных слов.
        """
        return self.valid_text(self.cleaned_data['name'])

    def clean_description(self):
        """
        Проверка описания продукта на наличие запрещенных слов.
        """
        return self.valid_text(self.cleaned_data['description'])


class ProductModeratorForm(ModelForm):
    """
    Форма модераторского редактирования продукта.
    """
    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published')


class VersionForm(StyleFormMixin, ModelForm):
    """
    Форма добавления и редактирования версии продукта.
    """
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView

from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Version, Category
from catalog.servises import get_categories_from_cache


class ProductListView(ListView):
    """
    Вывод списка всех продуктов
    """
    model = Product


class ProductDetailView(LoginRequiredMixin, DetailView):
    """
    Вывод детальной страницы продукта
    """
    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    """
    Вывод формы создания нового продукта
    """
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_views')

    def form_valid(self, form):
        product = form.save()
        product.owner = self.request.user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    """
    Вывод формы редактирования продукта
    """
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_views')

    def get_success_url(self):
        """
        Возвращает URL для перехода на детальную страницу продукта после успешного редактирования
        """
        return reverse('catalog:product_detail', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        """
        Добавляет форму версии продукта к контексту
        """
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        """
        Проверка формы и формы версии на правильность заполнения
        """
        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            versions = Version.objects.filter(product=self.object, current_version_flag=True)
            if len(versions) > 1:
                form.add_error(None, 'У продукта не может быть более одной активной версии.')
                return super().form_invalid(form)
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get_form_class(self):
        user = self.request.user
        if self.object.owner == user or user.is_superuser:
            return ProductForm
        if user.has_perm("catalog.can_edit_is_published") and user.has_perm("catalog.can_edit_description") and user.has_perm("catalog.can_edit_category"):
            return ProductModeratorForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    Вывод формы удаления продукта
    """
    model = Product
    success_url = reverse_lazy('catalog:product_views')

    def test_func(self):
        """
        Проверка пользователя на superuser
        """
        return self.request.user.is_superuser


class ContactView(TemplateView):
    """
    Вывод страницы контактов
    """
    template_name = "catalog/contacts.html"

    def post(self, request):
        """
        Отправка POST запроса с формы контактов

        """
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        message = request.POST.get("message")
        print(f"{name}({phone}) - {message}")
        return render(request, "catalog/contacts.html")


class CategoryListView(LoginRequiredMixin, ListView):
    """
    Вывод списка всех категорий продуктов
    """
    model = Category

    def get_queryset(self):
        """
        Получение данных
        """
        return get_categories_from_cache()

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> Супермаркет "Халява"</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
{% include 'catalog/includes/inc_menu.html' %}

{% block content %}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Список категорий продуктов</h1>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card-body">
                <ul>
                    {% for category in object_list %}
                    <li>
                        <h2>{{ category }}</h2>
                    </li>
                    {% endfor %}
                </ul>


                <a class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'catalog:product_views' %}"
                   role="button">Назад</a>

            </div>

        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html'%}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% if object.images %}
                    <img class="card-img-top" src="{{ object.images| mymedia }}"
                         style="max-width: 600px; max-height: 400px">
                    {% else %}
                    <img src="/media/product/dd70ce88-0468-427b-9b4b-e3b4b4ddf6f0.jpeg"
                         style="max-width: 400px; max-height: 190px">
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить карточку продукта "{{ object }}"</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'catalog:product_detail' object.pk %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="container">

    <div class="row text-center">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card mb-4 box-shadow">

                <div class="card-header">
                    <h1 class="my-0 font-weight-normal">{{ object.name }}</h1>
                </div>

                <div class="card-body">
                    {% if object.images %}
                    <img class="card-img-top" src="{{ object.images| mymedia }}"
                         style="max-width: 600px; max-height: 400px">
                    {% else %}
                    <img src="/media/product/dd70ce88-0468-427b-9b4b-e3b4b4ddf6f0.jpeg"
                         style="max-width: 400px; max-height: 190px">
                    {% endif %}

                    {% if not object.price %}
                    <h1 class="card-title pricing-card-title">Не указано</h1>
                    {% else %}
                    <h1 class="card-title pricing-card-title">{{ object.price }} руб.</h1>
                    {% endif %}
                    <p> {{ object.description }}</p>
                    <button type="button" class="btn btn-lg btn-block btn-outline-success">Купить</button>
                    {% if perms.catalog.can_edit_is_published and perms.catalog.can_edit_description and perms.catalog.can_edit_category or object.owner == user or user.is_superuser %}
                    <a class="btn btn-lg btn-block btn-outline-warning"
                       href="{% url 'catalog:product_update' object.pk %} "
                       role="button">Изменить</a>
                    {% endif %}
                    {% if user.is_superuser %}
                    <a class="btn btn-lg btn-block btn-outline-danger"
                       href="{% url 'catalog:product_delete' object.pk %} "
                       role="button">Удалить</a>
                    {% endif %}
                    <a href="{% url 'catalog:product_views' %}" type="button"
                       class="btn btn-lg btn-block btn-outline-primary">Назад</a>

                </div>

            </div>
        </div>
    </div>

    {% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        {% if object %}
                        <h3 class="card-title"> Редактирование информации о продукте</h3>
                        {% else %}
                        <h3 class="card-title"> Создание продукта</h3>
                        {% endif %}
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p}}
                        <button type="submit" class="btn btn-success">
                            {% if not object %}
                            Создать
                            {% else %}
                            Обновить
                            {% endif %}
                        </button>
                        {% if object %}
                        <a href="{% url 'catalog:product_detail' object.pk%}" type="button"
                           class="btn btn-danger">Отмена</a>
                        {% else %}
                        <a href="{% url 'catalog:product_views' %}" type="button" class="btn btn-danger">Отмена</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% if object %}
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title"> Выбор текущей версии</h3>
                    </div>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                        {{ form.as_p}}
                        {% if not forloop.last %}
                        <hr>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endif %}
        </form>
    </div>

    {% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Магазин дешевых цен</h1>
    <p class="lead">Покупай в один клик - экономь на низких ценах</p>
</div>

<div class="container">
    <div class="row text-center">
        <p>
            {% if user.is_authenticated %}
            <a class="btn btn-lg btn-block btn-outline-warning"
               href="{% url 'catalog:product_create' %} "
               role="button">Добавить продукт</a>
            {% endif %}
        </p>

        {% for product in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow" style="max-width: 600px; height: 550px">

                {% if product.images %}
                <img src="{{ product.images| mymedia }}" style="max-width: 400px; max-height: 190px">
                {% else %}
                <img src="/media/product/dd70ce88-0468-427b-9b4b-e3b4b4ddf6f0.jpeg"
                     style="max-width: 400px; max-height: 190px">
                {% endif %}

                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                </div>
                <div class="card-body">
                    {% if not product.price %}
                    <h1 class="card-title pricing-card-title">Не указано</h1>
                    {% else %}
                    <h1 class="card-title pricing-card-title">{{ product.price }} руб.</h1>
                    {% endif %}
                    <p> {{ product.description | truncatechars:100 }}</p>


                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                    <a class="btn btn-lg btn-block btn-outline-primary"
                       href="{% url 'catalog:product_detail' product.pk %} "
                       role="button">Подробнее</a>

                </div>
                <div class="card-footer">
                    {% if product.active_version %}
                    Версия {{ product.active_version }}
                    {% else %}
                    Версия не указана
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    {% endblock %}